main:
	gcc -o signaltest signaltest.c
	gcc -o signalactiontest signalactiontest.c
	gcc -o settimertest settimertest.c
	gcc -o alarmtest alarmtest.c
	gcc -o siginttest siginttest.c
	gcc -o pipetest pipetest.c
	gcc -o fifotest1 fifotest1.c
	gcc -o fifotest2 fifotest2.c
clean:
	rm signaltest
	rm signalactiontest
	rm settimertest
	rm alarmtest
	rm siginttest
	rm pipetest
	rm fifotest1
	rm fifotest2
