main:
	gcc -o signaltest signaltest.c
	gcc -o signalactiontest signalactiontest.c
	gcc -o settimertest settimertest.c
	gcc -o alarmtest alarmtest.c
clean:
	rm signaltest
	rm signalactiontest
	rm settimertest
	rm alarmtest
